In [5]:
import mdtraj as md
import msmbuilder
import numpy as np

In [3]:
filepath = '/Users/bren/desktop/msk/sonya-traj/run0-clone0.h5'
trajs = md.load(filepath)


In [6]:
np.array(trajs.xyz).shape

(25000, 4916, 3)

In [7]:
trajs=trajs.xyz

In [10]:
print (trajs[0])

[[-0.537       5.32300043  8.29900074]
 [-0.45700002  5.33600044  8.36000061]
 [-0.60500002  5.26400042  8.34400082]
 ..., 
 [ 2.79400015  1.00100005  9.38800049]
 [ 2.66600013  1.02100003  9.38199997]
 [ 2.86500025  0.95200002  9.29400063]]


In [15]:
from class_obs_tica import ObservableTicaObject

ModuleNotFoundError: No module named 'class_obs_tica'

In [16]:
import sys
sys.path.insert(0, '/Users/Bren/Documents/Github/observable-tica/tica-class')

from class_obs_tica import ObservableTicaObject


In [17]:
a = ObservableTicaObject